### ISSUE TITLE
Rework database to utelize JUST Redis

### ISSUE THREAD

**Issue by LeechFilcher** [pamaxie/Pamaxie#43]
We want to go away from having a seperate SQL database for the Website. This means all of our stuff should use JUST Redis, please think of a data storage concept n stuff if you feel like it and post it here.

**Comment by PKoldborg** [comment]
All visual errors have been fixed.
Do remember to check the TODO list, as some features are not added yet, that are needed.
Example, check if the database is running. Both Pamaxie.Api and Pamaxie.Website checks this in Startup.cs

**Comment by LeechFilcher** [comment]
Reworking the Server side today. Client side needs to be reworked after Pamaxie.Database.API is finished. Moving the database / data storage projects into a different folder once done.

**Comment by LeechFilcher** [comment]
Reworking the database has been almost completed now. We will use Swagger to auto generate a client for the API, to make it easier for us to maintain our steadily growing codebase and reduce complexity. The server side needs to be documented (however this can be done outside this ticket). We now employed a dynamic approach meaning by dropping another assembly with the required classes into the project anyone can implement their own database driver for pamaxie.

**Comment by LeechFilcher** [comment]
Database Rework has been finished. We now just need to implement the Database API
