### ISSUE TITLE
Use / Update APIs to use proper status codes

### ISSUE THREAD

**Issue by LeechFilcher** [pamaxie/Pamaxie#52]
We need to adhere to HTTP status code standards and not just return what ever we want.
If you need help on fixing this status codes can be found here:
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
Its OK to use unofficial codes as long as they are unique and describe the error clearly. 
Creating new Status codes should be documented here. Also make sure they do NOT conflict with existing status codes of any of the status codes on that website (official or not doesn't matter).

**Comment by PKoldborg** [comment]
Closing as this is done.
